import React, { useState, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { Download, Printer, RefreshCcw, BookOpen, HeartPulse, CreditCard, Stethoscope, FileText } from 'lucide-react';
import { UserData } from '../types';

interface ResultsViewProps {
  markdownContent: string;
  onReset: () => void;
  userData: UserData;
}

export const ResultsView: React.FC<ResultsViewProps> = ({ markdownContent, onReset, userData }) => {
  const [showSpanish, setShowSpanish] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  const handlePrint = (e: React.MouseEvent) => {
    e.preventDefault();
    // Focus ensures the window is active which helps with print dialogs in some iframe contexts
    window.focus();
    setTimeout(() => {
      window.print();
    }, 100);
  };

  const handleDownloadDoc = () => {
    if (!contentRef.current) return;
    
    // Get the HTML content directly from the rendered markdown
    // We wrap it in a standard HTML structure with Word-compatible namespaces
    const contentHtml = contentRef.current.innerHTML;
    const fullHtml = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <title>Jalisco Health Care Plan Blueprint</title>
        <style>
          body { font-family: 'Calibri', 'Arial', sans-serif; font-size: 11pt; line-height: 1.5; }
          h1 { font-size: 18pt; color: #115e59; }
          h2 { font-size: 14pt; color: #134e4a; margin-top: 20px; }
          h3 { font-size: 12pt; font-weight: bold; color: #ea580c; }
          ul { margin-bottom: 10px; }
          li { margin-bottom: 5px; }
        </style>
      </head>
      <body>
        ${contentHtml}
        <br/>
        <p style="font-size: 9pt; color: #666;">Generated by Jalisco Health Care Plan Tool</p>
      </body>
      </html>
    `;

    const blob = new Blob(['\ufeff', fullHtml], {
      type: 'application/msword'
    });
    
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Jalisco_Health_Care_Blueprint.doc';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Categorized vocabulary for the "Surprise" feature
  const vocabulary = {
    emergencies: [
      { es: "¡Ayuda!", en: "Help!" },
      { es: "Necesito una ambulancia", en: "I need an ambulance" },
      { es: "¿Dónde están las Urgencias?", en: "Where is the Emergency Room?" },
      { es: "Tengo dolor severo", en: "I have severe pain" },
      { es: "Infarto / Ataque al corazón", en: "Heart attack" },
    ],
    admin: [
      { es: "¿Aceptan tarjeta de crédito?", en: "Do you accept credit cards?" },
      { es: "Necesito una factura", en: "I need an itemized invoice (crucial for insurance)" },
      { es: "Mi seguro es...", en: "My insurance is..." },
      { es: "No tengo seguro", en: "I don't have insurance" },
      { es: "Depósito", en: "Deposit" },
    ],
    basics: [
      { es: "Médico / Doctor", en: "Doctor" },
      { es: "Enfermera", en: "Nurse" },
      { es: "Farmacia", en: "Pharmacy" },
      { es: "Sangre", en: "Blood" },
      { es: "Presión alta", en: "High blood pressure" },
      { es: "Soy alérgico a...", en: "I am allergic to..." },
    ]
  };

  return (
    <div className="animate-fade-in pb-10">
      {/* Action Bar */}
      <div className="bg-white p-4 rounded-lg shadow-md mb-6 border-l-4 border-terra-500 no-print action-bar">
        <div className="flex flex-wrap gap-4 justify-between items-center mb-2 sm:mb-0">
          <div>
            <h2 className="font-bold text-lg text-teal-900">Your Blueprint is Ready!</h2>
            <p className="text-sm text-stone-500">Review below, save as PDF, or download Word doc.</p>
          </div>
          <div className="flex flex-col items-end gap-1">
             <div className="flex gap-2">
                <button type="button" onClick={handlePrint} className="flex items-center gap-2 px-4 py-2 bg-stone-100 hover:bg-stone-200 rounded-lg text-stone-700 font-semibold transition-colors border border-stone-300" title="Opens the print dialog. Select 'Save as PDF' as your printer destination.">
                  <Printer className="w-4 h-4" /> <span className="hidden sm:inline">Print / Save as PDF</span>
                </button>
                <button type="button" onClick={handleDownloadDoc} className="flex items-center gap-2 px-4 py-2 bg-teal-700 hover:bg-teal-800 rounded-lg text-white font-semibold transition-colors" title="Download as a Word Document">
                  <FileText className="w-4 h-4" /> <span className="hidden sm:inline">Download .doc</span>
                </button>
             </div>
             <p className="text-xs text-terra-600 font-bold mt-2 text-center">
               If print button fails: Right-Click anywhere &gt; Print
             </p>
          </div>
        </div>
      </div>

      {/* Toggle Spanish Card (Surprise Feature) */}
      <div className="mb-6 no-print">
        <button 
          onClick={() => setShowSpanish(!showSpanish)}
          className="w-full bg-gradient-to-r from-teal-800 to-teal-900 text-white p-4 rounded-lg flex items-center justify-between hover:shadow-lg transition-all border border-teal-700"
        >
          <div className="flex items-center gap-3">
             <BookOpen className="w-6 h-6 text-terra-500" />
             <div className="text-left">
               <span className="font-bold text-lg block">English / Spanish Medical Phrasebook</span>
               <span className="text-teal-200 text-sm font-light">Click to open useful terms for emergencies & payments</span>
             </div>
          </div>
          <span className="text-sm font-semibold bg-teal-950 px-3 py-1 rounded-full">{showSpanish ? 'Close' : 'Open'}</span>
        </button>
        
        {showSpanish && (
          <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-4 animate-fade-in">
            
            {/* Emergencies */}
            <div className="bg-red-50 border border-red-100 rounded-xl p-4">
              <div className="flex items-center gap-2 mb-3 text-red-800 font-serif font-bold border-b border-red-200 pb-2">
                <HeartPulse className="w-5 h-5" /> Emergencies
              </div>
              <div className="space-y-3">
                {vocabulary.emergencies.map((item, i) => (
                  <div key={i}>
                    <p className="font-bold text-stone-800">{item.es}</p>
                    <p className="text-sm text-stone-500 italic">{item.en}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Money & Admin */}
            <div className="bg-emerald-50 border border-emerald-100 rounded-xl p-4">
              <div className="flex items-center gap-2 mb-3 text-emerald-800 font-serif font-bold border-b border-emerald-200 pb-2">
                <CreditCard className="w-5 h-5" /> Money & Admin
              </div>
              <div className="space-y-3">
                {vocabulary.admin.map((item, i) => (
                  <div key={i}>
                    <p className="font-bold text-stone-800">{item.es}</p>
                    <p className="text-sm text-stone-500 italic">{item.en}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Basics */}
            <div className="bg-blue-50 border border-blue-100 rounded-xl p-4">
              <div className="flex items-center gap-2 mb-3 text-blue-800 font-serif font-bold border-b border-blue-200 pb-2">
                <Stethoscope className="w-5 h-5" /> Basics
              </div>
              <div className="space-y-3">
                {vocabulary.basics.map((item, i) => (
                  <div key={i}>
                    <p className="font-bold text-stone-800">{item.es}</p>
                    <p className="text-sm text-stone-500 italic">{item.en}</p>
                  </div>
                ))}
              </div>
            </div>

          </div>
        )}
      </div>

      {/* Markdown Report Container */}
      <div className="bg-white p-8 sm:p-12 rounded-xl shadow-xl print:shadow-none print:p-0">
        <article ref={contentRef} className="prose prose-stone prose-lg max-w-none prose-headings:text-teal-900 prose-h1:font-serif prose-h2:font-serif prose-a:text-terra-600 hover:prose-a:text-terra-700 prose-strong:text-teal-800">
          <ReactMarkdown>
            {markdownContent}
          </ReactMarkdown>
        </article>
      </div>

      <div className="mt-8 text-center no-print">
        <button onClick={onReset} className="text-stone-400 hover:text-stone-600 flex items-center gap-2 mx-auto">
           <RefreshCcw className="w-4 h-4" /> Start Over
        </button>
      </div>
    </div>
  );
};
